- build: 1.7.2/centos/7
  image:
    - mesoscloud/elasticsearch:1.7.2-centos-7
    - mesoscloud/elasticsearch:1.7.2-centos
    - mesoscloud/elasticsearch:1.7.2
    - mesoscloud/elasticsearch:latest

- build: 1.7.2/ubuntu/14.04
  image:
    - mesoscloud/elasticsearch:1.7.2-ubuntu-14.04
    - mesoscloud/elasticsearch:1.7.2-ubuntu

- build: 1.7.1/centos/7
  image:
    - mesoscloud/elasticsearch:1.7.1-centos-7
    - mesoscloud/elasticsearch:1.7.1-centos
    - mesoscloud/elasticsearch:1.7.1

- build: 1.7.1/ubuntu/14.04
  image:
    - mesoscloud/elasticsearch:1.7.1-ubuntu-14.04
    - mesoscloud/elasticsearch:1.7.1-ubuntu


- tests:
    - cmd: elasticsearch -v
    - cmd: curator --version
